config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "example.com"
  devise_for :users
  root to: "users#home"
  resources :users, except: [:edit, :update, :create] do
    collection do
      get 'my_phases'
      get 'phase_requests'
      post 'create_user'
    end
  end
  resources :user_roles, except: [:edit, :update]
  resources :roles, except: [:edit, :update]
  resources :leads, except: [:edit, :update] do
    patch 'mark_complete', on: :member
    resources :phases, shallow: true, only: [:create, :show, :destroy] do 
      member do
        get 'accept_decline'
        patch 'set_phase_status'
        patch 'mark_complete'
        get 'add_engineer'
      end
    end
  end
  resources :projects, only: [:index]
  resources :comments, only: [:create, :destroy]
  resources :phase_assignments, only: [:create, :show, :destroy] do
    get 'generate_form', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :phase
  belongs_to :user

  # validates :comment_body, :phase_id, :user_id, presence: true
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user
  has_many :phases, dependent: :delete_all
  has_one :project_lead, dependent: :destroy

  validates :project_name, :client_name, :client_email, :client_contact, :client_address, :platform, presence: true
end

app/models/phase.rb
class Phase < ApplicationRecord
  belongs_to :lead
  belongs_to :user
  has_many :phase_assignments, dependent: :delete_all
  has_many :users, through: :phase_assignment
  has_many :comments, dependent: :delete_all

  validates :phase_type, :start_date, :due_date, :phase_status, presence: true
end

app/models/phase_assignment.rb
class PhaseAssignment < ApplicationRecord
  belongs_to :user  
  belongs_to :phase  

  # validates :phase_type, :start_date, :due_date, :phase_status, :lead_id, presence: true
end

app/models/project_lead.rb
class ProjectLead < ApplicationRecord
  belongs_to :lead

  # validates :comment_body, :phase_id, :user_id, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_role

  # validates :role_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_roles
  has_many :roles, through: :user_role
  has_many :leads
  has_many :phase_assignments
  has_many :phases, through: :phase_assignment
  has_many :comments
  has_many :phases
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role 

  # validates :role_id, :user_id, presence: true
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  def index
    @leads = Lead.all
  end

  def new
    @lead = Lead.new
  end

  def update
    user.update(name: 'asdjbasjh')
  end

  def after_update
    user.update(user_name: ;lm)
  end

  def create
    @lead = Lead.new(strip_lead_parameters)
    if @lead.save
      flash[:notice] = "Lead was successfully started!"
      redirect_to leads_path
    else
      flash[:alert] = "Error! Couldn't start the lead!"
      render :new
    end
  end

  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy
    flash[:notice] = "Lead was deleted successfully"
    redirect_to leads_path
  end

  def show
    @lead = Lead.find(params[:id])
    @phases = @lead.phases.reverse
    @comment_size = 0
    @user_size = 0
    @lead.phases.each do |phase|
      @comment_size = @comment_size + phase.comments.size
    end
    @phases.each do |phase|
      @user_size = @user_size + phase.phase_assignments.size
    end
    @phase = Phase.new
    @managers = Role.find_by(role_name: "Technical Manager").user_roles
  end

  def mark_complete
    @lead = Lead.find(params[:id])
    if @lead.phases.where.not(phase_status: "Complete").size > 0
      flash[:alert] = "This lead has incomplete phases. Complete all phases to start transitioning to sale"
    else
      @lead.status = "Complete"
      @lead.save
      @project_lead = ProjectLead.new(project_name: @lead.project_name, lead_id: @lead.id)
      @project_lead.save
      flash[:notice] = "Lead has successfully been marked as sale and a project has generated."
    end
    redirect_to lead_path(params[:id])
  end

  private
  def strip_lead_parameters
    params.require(:lead).permit(:project_name, :client_name, :client_email, :client_contact, :client_address, :platform, :status, :user_id)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @roles = Role.all
  end

  def destroy
    @role = Role.find(params[:id])
    @role.destroy
    flash[:notice] = "Role has successfully been deleted!"

    redirect_to roles_path
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(strip_role_params)
    if @role.save
      flash[:notice] = "New role has successfully been added!"
      redirect_to roles_path
    else
      flash[:alert] = "New role couldn't be added"
      render :new
    end
  end

  private
  def strip_role_params
    params.require(:role).permit(:role_name)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :check_user_session

  # Dashboard
  def index
  end

  # All Users
  def all_users
    @users = User.all
  end

  # Add User
  def new_user
    @user = User.new
    @roles = Role.all
  end

  def create_user
    @user = User.new(strip_user_params)
    if @user.save
      flash[:notice] = "User created successfully!"
      redirect_to all_users_path
    else
      flash[:alert] = "User couldn't be created!"
      render :new_user
    end
  end

  def destroy_user
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User deleted successfully!"

    redirect_to all_users_path
  end

  def assign_roles
    @user_role = UserRole.new
    @users = User.all
    @roles = Role.all
  end

  def create_role
    @user_role = UserRole.new(strip_user_role_params)
    if @user_role.save
      flash[:notice] = "User has successfully been assigned the role!"
      redirect_to assign_roles_path
    else
      flash[:alert] = "Error! Couldn't assign role"
      render :assign_roles
    end
  end

  def my_phases
    @phases = Phase.all.where(user_id: current_user.id)
  end

  private

  def check_user_session
    authenticate_user!
    # if not user_signed_in?
    #   redirect_to "devise/sessions/new"
    #   # render "devise/sessions/new"
    # end
  end

  def strip_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def strip_user_role_params
    params.require(:user_role).permit(:user_id, :role_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/dashboard/_footer.html.erb
<footer class="main-footer">
  <div class="footer-left">
    Copyright &copy; 2021 DEVSINC<div class="bullet"></div> Developed By <a href="https://github.com/abdulhyie" target="_blank">Abdul Hai</a>
  </div>
  <div class="footer-right">
    
  </div>
</footer>

app/views/dashboard/_header.html.erb
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
  <form class="form-inline mr-auto">
    <ul class="navbar-nav mr-3">
      <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
    </ul>
  </form>
  <ul class="navbar-nav navbar-right">
    <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
      <%= image_tag "avatar-1.png", class: "rounded-circle mr-1" %>
      <%# <img alt="image" src="../assets/img/avatar/avatar-1.png" class="rounded-circle mr-1"> %>
      <div class="d-sm-none d-lg-inline-block">Hi, <%= current_user.name %></div></a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-title">Logged in 5 min ago</div>
        <a href=<%= edit_user_registration_path %> class="dropdown-item has-icon">
          <i class="far fa-user"></i> Profile
        </a>
        <a href="features-activities.html" class="dropdown-item has-icon">
          <i class="fas fa-bolt"></i> Activities
        </a>
        <a href="features-settings.html" class="dropdown-item has-icon">
          <i class="fas fa-cog"></i> Settings
        </a>
        <div class="dropdown-divider"></div>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item has-icon text-danger" %>
        
      </div>
    </li>
  </ul>
</nav>

app/views/dashboard/_navbar.erb
<div class="main-sidebar">
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand">
      <a href=<%= root_path %>>Lead Management</a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
      <a href=<%= root_path %>>LM</a>
    </div>
    <ul class="sidebar-menu">
      <li class="active"><a class="nav-link" href=<%= root_path %>><i class="fas fa-fire"></i> <span>Dashboard</span></a></li>
      <li class="menu-header">Leads & Projects</li>
      <li class=""><a class="nav-link" href=<%= leads_path %>><i class="fas fa-stream"></i> <span>All Leads</span></a></li>
      <li class=""><a class="nav-link" href=<%= my_phases_users_path %>><i class="fas fa-file-alt"></i> <span>My Phases</span></a></li>
      <li class=""><a class="nav-link" href=<%= projects_path %>><i class="fas fa-project-diagram"></i> <span>All Projects</span></a></li>
      <% if user_is?("Super Admin") || user_is?("Business Developer") %>
        <li class=""><a class="nav-link" href=<%= new_lead_path %>><i class="fas fa-dice-d6"></i> <span>Initiate Lead</span></a></li>
        <li class=""><a class="nav-link" href=<%= phase_requests_users_path %>><i class="fas fa-tasks"></i> <span>Phase Requests</span></a></li>
      <% end %>
      <% if user_is?("Super Admin") %>
        <li class="menu-header">Manage Users</li>
        <li class=""><a class="nav-link" href=<%= users_path %>><i class="fas fa-users"></i> <span>All Users</span></a></li>
        <li class=""><a class="nav-link" href=<%= new_user_path %>><i class="fas fa-user-plus"></i> <span>Add User</span></a></li>
        <li class=""><a class="nav-link" href=<%= new_user_role_path %>><i class="fas fa-id-badge"></i> <span>Assign Roles</span></a></li>
        <li class="menu-header">Manage Roles</li>
        <li class=""><a class="nav-link" href=<%= roles_path %>><i class="fas fa-briefcase"></i> <span>All Roles</span></a></li>
        <li class=""><a class="nav-link" href=<%= new_role_path %>><i class="fas fa-plus"></i> <span>Add Roles</span></a></li>
        <li class=""><a class="nav-link" href=<%= user_roles_path %>><i class="fas fa-directions"></i> <span>View Assigned Roles</span></a></li>
      <% end %>
      <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-primary btn-lg btn-block btn-icon-split" %>
      </div>
    </ul>
  </aside>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', 'component', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- include summernote css/js -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
  </head>
  <body>
    <%= yield %>

    <!-- General JS Scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <%= javascript_pack_tag "stisla" %>
    <%= javascript_pack_tag "script" %>

    <%# Toastr Alerts %>
    <% if flash.any? %>
      <script type="text/javascript">
        <% flash.each do |key, value| %>
          <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          toastr.<%= type %>('<%= value %>')
        <% end %>
      </script>
    <% end %>

    <%# Summernote initialize %>
    <script>
      $(document).ready(function() {
        $('#summernote').summernote({
          height: 230,
          toolbar: [
            // [groupName, [list of button]]
            ['style', ['bold', 'italic', 'underline', 'clear']],
            ['font', ['strikethrough', 'superscript', 'subscript']],
            ['fontsize', ['fontsize']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['height', ['height']]
          ]
        });
      });
    </script>
    
  </body>
</html>