config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "example.com"
  devise_for :users
  root to: "users#home"
  resources :users, except: [:edit, :update, :create] do
    collection do
      get 'my_phases'
      get 'phase_requests'
      post 'create_user'
    end
  end
  resources :user_roles, except: [:edit, :update]
  resources :roles, except: [:edit, :update]
  resources :leads, except: [:edit, :update] do
    patch 'mark_complete', on: :member
    resources :phases, shallow: true, only: [:create, :show, :destroy] do 
      member do
        get 'accept_decline'
        patch 'set_phase_status'
        patch 'mark_complete'
        get 'add_engineer'
      end
    end
  end
  resources :projects, only: [:index]
  resources :comments, only: [:create, :destroy]
  resources :phase_assignments, only: [:create, :show, :destroy] do
    get 'generate_form', on: :member
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_roles
  has_many :roles, through: :user_role
  has_many :leads
  has_many :phase_assignments
  has_many :phases, through: :phase_assignment
  has_many :comments
  has_many :phases
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :check_user_session

  # Dashboard
  def index
  end

  # All Users
  def all_users
    @users = User.all
  end

  # Add User
  def new_user
    @user = User.new
    @roles = Role.all
  end

  def create_user
    @user = User.new(strip_user_params)
    if @user.save
      flash[:notice] = "User created successfully!"
      redirect_to all_users_path
    else
      flash[:alert] = "User couldn't be created!"
      render :new_user
    end
  end

  def destroy_user
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User deleted successfully!"

    redirect_to all_users_path
  end

  def assign_roles
    @user_role = UserRole.new
    @users = User.all
    @roles = Role.all
  end

  def create_role
    @user_role = UserRole.new(strip_user_role_params)
    if @user_role.save
      flash[:notice] = "User has successfully been assigned the role!"
      redirect_to assign_roles_path
    else
      flash[:alert] = "Error! Couldn't assign role"
      render :assign_roles
    end
  end

  def my_phases
    @phases = Phase.all.where(user_id: current_user.id)
  end

  private

  def check_user_session
    authenticate_user!
    # if not user_signed_in?
    #   redirect_to "devise/sessions/new"
    #   # render "devise/sessions/new"
    # end
  end

  def strip_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def strip_user_role_params
    params.require(:user_role).permit(:user_id, :role_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_user_session
  before_action :check_authorization, only: [:all_users, :new_user, :create_user, :assign_roles, :destroy_user, :create_role]

  # All Users
  def index
    @users = User.all
  end

  # Dashboard
  def home
    @users = User.all
  end

  # Add User
  def new
    @user = User.new
    @roles = Role.all
  end

  def create_user
    @user = User.new(strip_user_params)
    if @user.save
      flash[:notice] = "User created successfully!"
      redirect_to users_path
    else
      flash[:alert] = "User couldn't be created!"
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User deleted successfully!"

    redirect_to users_path
  end

  def my_phases
    @phases = Phase.all.where(user_id: current_user.id)
  end

  def phase_requests
    @phase_reqs = current_user.phases.where(phase_status: "Awaiting Manager")
  end

  private

  def check_authorization

    if not user_is?("Super Admin")
      flash[:alert] = "You are not authorized to view this page."
      redirect_to root_path
    end

  end

  def check_user_session
    authenticate_user!

    # if not user_signed_in?
    #   redirect_to "devise/sessions/new"
    #   # render "devise/sessions/new"
    # end
  end

  def strip_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def strip_user_role_params
    params.require(:user_role).permit(:user_id, :role_id)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/home.html.erb
<div id="app">
    <div class="main-wrapper">

      <%= render "dashboard/header" %>
      <%= render "dashboard/navbar" %>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Dashboard</h1>
          </div>
          <div class="row">
            <div class="col-12 mb-4">
              <div class="hero bg-primary text-white">
                <div class="hero-inner">
                  <h2>Welcome Back, <%= current_user.name %>!</h2>
                  <p class="lead">Lead Management System.</p>
                  <div class="mt-4">
                    <a href=<%= edit_user_registration_path %> class="btn btn-outline-white btn-lg btn-icon icon-left"><i class="far fa-user"></i>Account Details</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
              <div class="card card-statistic-1">
                <div class="card-icon bg-primary">
                  <i class="far fa-user"></i>
                </div>
                <div class="card-wrap">
                  <div class="card-header">
                    <h4>Total Users</h4>
                  </div>
                  <div class="card-body">
                    <%= User.all.size %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
              <div class="card card-statistic-1">
                <div class="card-icon bg-danger">
                  <i class="far fa-newspaper"></i>
                </div>
                <div class="card-wrap">
                  <div class="card-header">
                    <h4>Total Leads</h4>
                  </div>
                  <div class="card-body">
                    <%= Lead.all.size %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
              <div class="card card-statistic-1">
                <div class="card-icon bg-warning">
                  <i class="far fa-file"></i>
                </div>
                <div class="card-wrap">
                  <div class="card-header">
                    <h4>Total Phases</h4>
                  </div>
                  <div class="card-body">
                    <%= Phase.all.size %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
              <div class="card card-statistic-1">
                <div class="card-icon bg-success">
                  <i class="fas fa-circle"></i>
                </div>
                <div class="card-wrap">
                  <div class="card-header">
                    <h4>Total Projects</h4>
                  </div>
                  <div class="card-body">
                    <%= ProjectLead.all.size %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      <%= render "dashboard/footer" %>

    </div>
  </div>

app/views/users/index.html.erb
<div id="app">
    <div class="main-wrapper">

      <%= render "dashboard/header" %>
      <%= render "dashboard/navbar" %>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>All Users</h1>
          </div>
          <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h4>All Users</h4>
                  <div class="card-header-form">
                    <form>
                      <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <div class="input-group-btn">
                          <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
                <div class="card-body p-0">
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <tr>
                        <th>
                          <div class="custom-checkbox custom-control">
                            <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad" class="custom-control-input" id="checkbox-all">
                            <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                          </div>
                        </th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Prominant Role</th>
                        <th>Member Since</th>
                        <th>Action</th>
                      </tr>
                      <% @users.each do |user| %>
                      <tr>
                        <td class="p-0 text-center">
                          <div class="custom-checkbox custom-control">
                            <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input" id="checkbox-1">
                            <label for="checkbox-1" class="custom-control-label">&nbsp;</label>
                          </div>
                        </td>
                        <td><%= user.name %></td>
                        <td class="align-middle">
                          <%= user.email %>
                        </td>
                        <td>
                          <!-- <img alt="image" src="../assets/img/avatar/avatar-5.png" class="rounded-circle" width="35" data-toggle="tooltip" title="Wildan Ahdian"> -->
                          <% if user.user_roles.first %>
                            <%= user.user_roles.first.role.role_name %>
                          <% else %>
                            None
                          <% end %>
                        </td>
                        <td><%= user.created_at %></td>
                        <td>
                          <a href="#" class="btn btn-secondary">Details</a>
                          <%= link_to "Delete", user_path(user), method: :delete, class: "btn btn-danger" %>
                        </td>
                      </tr>
                      <% end %>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      <%= render "dashboard/footer" %>

    </div>
  </div>

app/views/users/my_phases.html.erb
<div id="app">
    <div class="main-wrapper">

      <%= render "dashboard/header" %>
      <%= render "dashboard/navbar" %>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>My Phases</h1>
          </div>
          <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h4>Phases</h4>
                  <div class="card-header-form">
                    <form>
                      <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <div class="input-group-btn">
                          <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
                <div class="card-body p-0">
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <tr>
                        <th>Phase Type</th>
                        <th>Start Date</th>
                        <th>Due Date</th>
                        <th>Lead Name</th>
                        <th>Phase Status</th>
                        <th>Technincal Manager</th>
                        <th>Action</th>
                      </tr>
                      <% @phases.each do |phase| %>
                      <tr>
                        <td><%= phase.phase_type %></td>
                        <td>
                          <%= phase.start_date.strftime("%m-%d-%Y") %>
                        </td>
                        <td>
                          <%= phase.due_date.strftime("%m-%d-%Y") %>
                        </td>
                        <td>
                          <%= phase.lead.project_name %> <br>
                        </td>
                        <td><%= phase.phase_status %></td>
                        <td><%= phase.user.name %></td>
                        <td>
                          <%= link_to "Phase Details", phase_path(phase.id), class: "btn btn-primary" %>
                        </td>
                      </tr>
                      <% end %>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      <%= render "dashboard/footer" %>

    </div>
  </div>

app/views/users/new.html.erb
<div id="app">
    <div class="main-wrapper">

      <%= render "dashboard/header" %>
      <%= render "dashboard/navbar" %>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Add New User</h1>
          </div>
          <div class="row">
            <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
              <div class="card card-primary">
                <div class="card-header"><h4>Add New User</h4></div>

                <div class="card-body">
                  <%= form_with model: @user, url: create_user_users_path do |f| %>
                    <div class="row">
                      <div class="form-group col-12">
                        <label for="first_name">Name</label>
                        <%= f.text_field :name, class: "form-control", required: "true", autocomplete: "off", autofocus: "true"%>
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="email">Email</label>
                      <%= f.text_field :email, class: "form-control", required: "true", type: "email", autocomplete: "off"%>
                      <div class="invalid-feedback">
                      </div>
                    </div>

                    <div class="row">
                      <div class="form-group col-6">
                        <label for="password" class="d-block">Password</label>
                        <%= f.text_field :password, class: "form-control", required: "true", type: "password"%>
                        <div id="pwindicator" class="pwindicator">
                          <div class="bar"></div>
                          <div class="label"></div>
                        </div>
                      </div>
                      <div class="form-group col-6">
                        <label for="password2" class="d-block">Password Confirmation</label>
                        <%= f.text_field :password_confirmation, class: "form-control", required: "true", type: "password"%>
                      </div>
                    </div>

                    <div class="form-divider">
                      Assign Role (Optional) <small class="text-small"> Can be assinged later as well </small>
                    </div>
                    <div class="row">
                      <div class="form-group col-12">
                        <label>Roles</label>
                        
                        <select class="form-control selectric">
                          <option selected="true">Select</option>
                          <option>Indonesia</option>
                          <option>Palestine</option>
                          <option>Syria</option>
                          <option>Malaysia</option>
                          <option>Thailand</option>
                        </select>
                      </div>
                    </div>

                    <div class="form-group">
                      <%= f.submit class: "btn btn-primary btn-lg btn-block"%>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      <%= render "dashboard/footer" %>

    </div>
</div>

app/views/users/phase_requests.html.erb
<div id="app">
    <div class="main-wrapper">

      <%= render "dashboard/header" %>
      <%= render "dashboard/navbar" %>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Phase Assignments</h1>
          </div>
          <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h4>Phases</h4>
                  <div class="card-header-form">
                    <form>
                      <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <div class="input-group-btn">
                          <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
                <div class="card-body p-0">
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <tr>
                        <th class="d-none"></th>
                        <th>Phase Type</th>
                        <th>Start Date</th>
                        <th>Due Date</th>
                        <th>Business Developer</th>
                        <th>Lead Name</th>
                        <th>Action</th>
                      </tr>
                      <% @phase_reqs.each do |phase| %>
                      <tr>
                        <td class="d-none"><%= phase.id %></td>
                        <td><%= phase.phase_type %></td>
                        <td>
                          <%= phase.start_date.strftime("%B %d, %Y") %>
                        </td>
                        <td class="align-middle">
                           <%= phase.due_date.strftime("%B %d, %Y") %>
                        </td>
                        <td>
                          <%= phase.user.name %> <br>
                        </td>
                        <td><%= phase.lead.project_name %></td>
                        <td>
                          <%= link_to "Accept / Decline", accept_decline_phase_path(phase), class: "btn btn-primary" %>
                        </td>
                      </tr>
                      <% end %>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      <%= render "dashboard/footer" %>

    </div>
  </div>