config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "example.com"
  devise_for :users
  root to: "users#home"
  resources :users, except: [:edit, :update, :create] do
    collection do
      get 'my_phases'
      get 'phase_requests'
      post 'create_user'
    end
  end
  resources :user_roles, except: [:edit, :update]
  resources :roles, except: [:edit, :update]
  resources :leads, except: [:edit, :update] do
    patch 'mark_complete', on: :member
    resources :phases, shallow: true, only: [:create, :show, :destroy] do 
      member do
        get 'accept_decline'
        patch 'set_phase_status'
        patch 'mark_complete'
        get 'add_engineer'
      end
    end
  end
  resources :projects, only: [:index]
  resources :comments, only: [:create, :destroy]
  resources :phase_assignments, only: [:create, :show, :destroy] do
    get 'generate_form', on: :member
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = ProjectLead.all
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
<div id="app">
    <div class="main-wrapper">

      <%= render "dashboard/header" %>
      <%= render "dashboard/navbar" %>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>All Projects</h1>
          </div>
          <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h4>Project</h4>
                  <div class="card-header-form">
                    <form>
                      <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <div class="input-group-btn">
                          <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
                <div class="card-body p-0">
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <tr>
                        <th>Project Name</th>
                        <th>Start Date</th>
                        <th>Lead Phases</th>
                        <th>Assigned BD</th>
                        <th>Action</th>
                      </tr>
                      <% @projects.each do |project| %>
                      <tr>
                        <td><%= project.project_name %></td>
                        <td>
                          <%= project.created_at.strftime("%m-%d-%Y") %>
                        </td>
                        <td>
                          <%= project.lead.phases.size %> <br>
                        </td>
                        <td><%= project.lead.user.name %></td>
                        <td>
                          <%= link_to "Lead Details", lead_path(project.lead.id), class: "btn btn-primary" %>
                          <%= link_to "Delete", project_path(project.id), method: :delete, class: "btn btn-danger" %>
                        </td>
                      </tr>
                      <% end %>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      <%= render "dashboard/footer" %>

    </div>
  </div>