config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "example.com"
  devise_for :users
  root to: "users#home"
  resources :users, except: [:edit, :update, :create] do
    collection do
      get 'my_phases'
      get 'phase_requests'
      post 'create_user'
    end
  end
  resources :user_roles, except: [:edit, :update]
  resources :roles, except: [:edit, :update]
  resources :leads, except: [:edit, :update] do
    patch 'mark_complete', on: :member
    resources :phases, shallow: true, only: [:create, :show, :destroy] do 
      member do
        get 'accept_decline'
        patch 'set_phase_status'
        patch 'mark_complete'
        get 'add_engineer'
      end
    end
  end
  resources :projects, only: [:index]
  resources :comments, only: [:create, :destroy]
  resources :phase_assignments, only: [:create, :show, :destroy] do
    get 'generate_form', on: :member
  end
end

app/controllers/phases_controller.rb
class PhasesController < ApplicationController

  before_action :check_user_session

  def show
    @phase = Phase.find(params[:id])
    @comments = @phase.comments.reverse
    @comment = Comment.new
  end

  def create
    @lead = Lead.find(params[:lead_id])
    @phase = @lead.phases.new(strip_phase_params)
    if @phase.save
      flash[:notice] = "Phase has been created. Email has been sent to the manager."
      AlertUsersMailer.notify_manager(@phase.user, @phase).deliver
      redirect_to lead_path(@lead)
    else
      flash[:alert] = "There was an error. Phase couldn't been added."
      redirect_to lead_path(@lead)
    end
  end

  def destroy
    @phase = Phase.find(params[:id])
    @lead_id = @phase.lead.id
    @phase.destroy
    flash[:notice] = "Phase has successfully been deleted."
    redirect_to lead_path(@lead_id)
  end

  def accept_decline
    @phase = Phase.find(params[:id])
  end

  def set_phase_status
    @phase = Phase.find(params[:id])
    @phase.update(strip_phase_params_update)
    redirect_to phase_requests_users_path
  end

  def add_engineer
    @phase = Phase.find(params[:id])
    @phase_assignment = PhaseAssignment.new
    @engineers = Role.find_by(role_name: "Engineer").user_roles
  end

  def add_multiple_engineers

  end

  def mark_complete
    @phase = Phase.find(params[:id])
    @phase.phase_status = "Complete"
    @phase.save
    flash[:notice] = "Phase has successfully been completed!"
    redirect_to lead_path(@phase.lead.id)
  end

  private
  
  def strip_phase_params
    params.require(:phase).permit(:start_date, :due_date, :user_id, :phase_type, :phase_status)
  end

  def strip_phase_params_update
    params.require(:phase).permit(:manager_comment, :phase_status)
  end

  def check_user_session
    authenticate_user!
  end
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/views/phases/_comment.html.erb
<li class="media">
  <%= image_tag "avatar-1.png", class: "mr-3 rounded-circle", width: "50" %>
  <div class="media-body">
    <% if comment.user.id == current_user.id %>
      <%= link_to "Delete", comment_path(comment.id), method: :delete, class: "float-right text-danger", data: {confirm: "Are you sure?"} %>
    <% end %>
    <div class="media-title"><%= comment.user.name %> <small class="text-small"><%= comment.user.email %></small> </div>
    <div class="text-primary text-small"><%= comment.created_at.strftime("%d %B, %Y, %I:%M %p") %></div>
    <span class="text-small text-muted"><%= raw comment.comment_body %></span>
  </div>
</li>

app/views/phases/accept_decline.html.erb
<div id="app">
  <section class="section">
    <div class="container mt-5">
      <div class="row">
        <div class="col-12 col-sm-12 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
          <div class="login-brand">
          </div>

          <div class="card card-primary">
            <div class="card-header"><h4>Accept or Decline</h4></div>

            <div class="card-body">
              <p> <%= @phase.lead.user.name %> <b>(BD)</b> has assigned you a phase for <%= @phase.lead.project_name %>.</p>
              <%= form_with model: @phase, url: set_phase_status_phase_path(@phase) do |f| %>
                <div class="form-group">
                  <%= f.label :manager_comment %><br />
                  <%= f.text_area(:manager_comment, autofocus: true, class: "form-control", id: "summernote") %>
                </div>

                <div class="form-group">
                  <label class="form-label">Action</label>
                  <div class="selectgroup w-100">
                    <label class="selectgroup-item">
                      <input type="radio" name="phase[phase_status]" value="Ongoing" class="selectgroup-input" checked="">
                      <span class="selectgroup-button">Accept</span>
                    </label>
                    <label class="selectgroup-item">
                      <input type="radio" name="phase[phase_status]" value="Declined by Manager" class="selectgroup-input">
                      <span class="selectgroup-button">Decline</span>
                    </label>
                  </div>
                </div>

                <div class="form-group actions">
                  <%= f.submit "Submit", class: "btn btn-primary btn-lg btn-block" %>
                </div>
              <% end %>

            </div>
          </div>
          <div class="simple-footer">
            Copyright &copy; DEVSINC 2021
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/phases/add_engineer.html.erb
<div id="app">
    <div class="main-wrapper">

      <%= render "dashboard/header" %>
      <%= render "dashboard/navbar" %>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Assign Engineer</h1>
          </div>
          <div class="row">
            <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
              <div class="card card-primary">
                <div class="card-header"><h4>Assign Engineer to this Phase</h4></div>

                <div class="card-body">
                  <%= form_with model: @phase_assignment do |f| %>
                    <%= f.hidden_field :phase_id, value: @phase.id %>
                    <div class="row">
                      <div class="form-group col-12">
                        <label>Engineer</label>
                        <%= f.select :user_id, @engineers.map { |u| [u.user.name + "  (" + u.user.email + ")", u.user.id]}, {prompt: "Select Engineer"}, class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <%= f.submit "Assign Engineer", class: "btn btn-primary btn-lg btn-block"%>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
              <div class="card card-primary">
                <div class="card-header"><h4>Assign Multiple Engineers to this Phase</h4></div>

                <div class="card-body">
                  <%= form_with url: generate_form_phase_assignment_path, method: :get do |f| %>
                    <%= f.hidden_field :phase_id, value: @phase.id %>
                    <div class="row">
                      <div class="form-group col-12">
                        <label>Number of engineers you want to add</label>
                        <%= f.text_field :num_selects, class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <%= f.submit "Generate Form", class: "btn btn-primary btn-lg btn-block"%>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      <%= render "dashboard/footer" %>

    </div>
</div>

app/views/phases/create_comment.js.erb
console.log("Now here");

app/views/phases/new.html.erb
new phase add here

app/views/phases/phase_requests.html.erb
<div id="app">
    <div class="main-wrapper">

      <%= render "dashboard/header" %>
      <%= render "dashboard/navbar" %>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Phase Assignments</h1>
          </div>
          <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h4>Phases</h4>
                  <div class="card-header-form">
                    <form>
                      <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <div class="input-group-btn">
                          <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
                <div class="card-body p-0">
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <tr>
                        <th class="d-none"></th>
                        <th>Phase Type</th>
                        <th>Start Date</th>
                        <th>Due Date</th>
                        <th>Business Developer</th>
                        <th>Lead Name</th>
                        <th>Action</th>
                      </tr>
                      <% @phase_reqs.each do |phase| %>
                      <tr>
                        <td class="d-none"><%= phase.id %></td>
                        <td><%= phase.phase_type %></td>
                        <td>
                          <%= phase.start_date.strftime("%B %d, %Y") %>
                        </td>
                        <td class="align-middle">
                           <%= phase.due_date.strftime("%B %d, %Y") %>
                        </td>
                        <td>
                          <%= phase.user.name %> <br>
                        </td>
                        <td><%= phase.lead.project_name %></td>
                        <td>
                          <%= link_to "Accept / Decline", "/phase_accept_decline/" + phase.id.to_s, class: "btn btn-primary" %>
                        </td>
                      </tr>
                      <% end %>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      <%= render "dashboard/footer" %>

    </div>
  </div>

app/views/phases/show.html.erb
<div id="app">
    <div class="main-wrapper">

      <%= render "dashboard/header" %>
      <%= render "dashboard/navbar" %>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Phase Information</h1>
          </div>

          <div class="row">
            <div class="col-lg-8 col-md-12 col-12 col-sm-12">
              <div class="card">
                <div class="card-header">
                  <h4>Phase</h4>
                  <div class="card-header-action">
                    <div class="">
                      <% if @phase.phase_status != "Complete" && @phase.user.id == current_user.id && @phase.phase_status != "Awaiting Manager" %>
                        <%= link_to "Mark as Complete", mark_complete_phase_path(@phase), method: :patch, class: "btn btn-primary" %>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                  <div class="row">
                    <h3 class="col-md-12 text-primary"><%= @phase.phase_type %></h3>
                    <h5 class="col-md-12 text-primary"><%= @phase.phase_status %></h5>
                  </div>
                  <div class="row" style="margin-top: 20px;">
                    <div class="col-md-6 col-sm-12">
                      <div class="list-group">
                        <a href="#" onclick="return false;" class="list-group-item list-group-item-action active">
                          <h5>Start Date</h5>
                        </a>
                        <a href="" onclick="return false;" class="list-group-item list-group-item-action"><%= @phase.created_at.strftime("%d %B, %Y, %I:%M %p") %></a>
                      </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                      <div class="list-group">
                        <a href="#" onclick="return false;" class="list-group-item list-group-item-action active">
                          <h5>Deadline</h5>
                        </a>
                        <a href="" onclick="return false;" class="list-group-item list-group-item-action"><%= @phase.due_date.strftime("%d %B, %Y, %I:%M %p") %></a>
                      </div>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <h6 class="col-md-12">Lead Information</h6>
                  </div>
                  <div class="row" style="margin-top: 20px;">
                    <div class="col-md-6 col-sm-12">
                      <div class="list-group">
                        <a href="#" onclick="return false;" class="list-group-item list-group-item-action active">
                          <h5>Start Date</h5>
                        </a>
                        <a href="" onclick="return false;" class="list-group-item list-group-item-action"><%= @phase.lead.created_at.strftime("%d %B, %Y, %I:%M %p") %></a>
                      </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                      <div class="list-group">
                        <a href="#" onclick="return false;" class="list-group-item list-group-item-action active">
                          <h5>Business Developer</h5>
                        </a>
                        <a href="" onclick="return false;" class="list-group-item list-group-item-action"><%= @phase.lead.user.name %></a>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="statistic-details mt-sm-4 ">
                  <div class="statistic-details-item">
                    <div class="detail-value"> <%= @phase.phase_assignments.size %> </div>
                    <div class="detail-name">Users Working</div>
                  </div>
                  <div class="statistic-details-item">
                    <div class="detail-value"> <%= @phase.comments.size %> </div>
                    <div class="detail-name">Comments</div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-12 col-12 col-sm-12">
              <div class="card author-box card-primary">
                <div class="card-header">
                  <h6>Phase Assignee</h6>
                </div>
                <div class="card-body">
                  <div class="author-box-left">
                    <%= image_tag "avatar-1.png", class: "rounded-circle author-box-picture" %>
                    <div class="clearfix"></div>
                  </div>
                  <div class="author-box-details">
                    <div class="author-box-name">
                      <a href="#"><%= @phase.user.name %></a>
                    </div>
                    <div class="author-box-job"><%= @phase.user.user_roles.first.role.role_name %></div>
                    <div class="author-box-job"><%= @phase.user.email %></div>
                  </div>
                </div>
                <% if @phase.user.id == current_user.id && @phase.phase_status != "Awaiting Manager" && @phase.phase_status != "Complete" %>
                  <div class="card-footer">
                    <a href=<%= add_engineer_phase_path(@phase) %> class="btn btn-primary float-right">Add Engineers</a>
                  </div>
                <% end %>
              </div>
              <%= link_to "All Engineers", phase_assignment_path(@phase), class: "col-md-12 btn btn-primary" %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <h4>Phase Comments</h4>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-12 col-md-12 col-12 col-sm-12">
            <div class="card">
              <div class="card-header">
                <h4>Technical Manager Comment</h4>
              </div>
              <div class="card-body">
                <ul class="list-unstyled list-unstyled-border">
                  <li class="media">
                    <%= image_tag "avatar-1.png", class: "mr-3 rounded-circle", width: "50" %>
                    <div class="media-body">
                      <div class="media-title"><%= @phase.user.name %> <small class="text-small"><%= @phase.user.email %></small></div>
                      <span class="text-small text-muted"><%= raw @phase.manager_comment %></span>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>            
          </div>

          <div class="row">
            <div class="col-lg-12 col-md-12 col-12 col-sm-12">
            <div class="card">
              <div class="card-header">
                <h4>All Comments</h4>
              </div>
              <div class="card-body">
                <ul class="list-unstyled list-unstyled-border" id="comments">
                  <%= render partial: "comment", collection: @comments %>
              </div>
            </div>
          </div>
          </div>

          <div class="row">
            <div class="col-lg-12 col-md-12 col-12 col-sm-12">
            <div class="card">
              <div class="card-header">
                <h4>Add a comment</h4>
              </div>
              <div class="card-body">
                <%= form_with model: @comment, remote: true do |f| %>

                <div class="form-group">
                  <label for="email">Comment Body <small class="text-small"> Mandatory</small> </label>
                  <%= f.text_area :comment_body, class: "form-control", required: "true", id: "summernote"%>
                  <div class="invalid-feedback">
                  </div>
                </div>

                <%= f.hidden_field :phase_id, value: @phase.id  %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                
            </div>
            <div class="modal-footer">
              <div class="row">
                <div class="form-group col-md-12">
                  <%= f.submit "Post Comment", class: "btn btn-primary btn-lg btn-block"%>
                </div>
              </div>
              <% end %>
              </div>
            </div>
          </div>            

        </section>
      </div>

      <%= render "dashboard/footer" %>

    </div>
  </div>